app/urls.py
from django.urls import path
from .views import home, category, views, about, contact

urlpatterns = [
    path('', home , name='home'),
    path('category/<slug:slug>/', category, name="category"),
    path('posts/<slug:slug>/', views, name="views"),
    path('about/', about, name="about"),
    path('contact/', contact, name="contact"),
]

config/urls.py
from django.contrib import admin
from django.urls import path ,include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/panel/', admin.site.urls),
    path('', include('app.urls')),
    path('users/', include('users.urls'), name="users"),
]
urlpatterns += static(settings.STATIC_URL , document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL , document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from .views import RegisterView , LoginView , ProfileView , LogoutView , ProfileUpdateView


app_name = "users"
urlpatterns = [
    path('register/', RegisterView.as_view() , name='register'),
    path('login/', LoginView.as_view() , name='login'),
    path('logout/', LogoutView.as_view() ,name='logout'),
    path('profile/<str:username>/', ProfileView.as_view() ,name="profile"),
    path('profile/<str:username>/edit/' , ProfileUpdateView.as_view() , name="profile_edit"),
]

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
# Create your models here.


class CustomUser(AbstractUser):
    profile_picture = models.ImageField(default="profile_default_picture.jpg", upload_to='profile_image')
    profession = models.CharField(max_length=250)


    def save(self, *args, **kwargs):
        super().save()

users/forms.py
from django import forms

from users.models import CustomUser


"""class UserCreateForm(forms.Form):
    username = forms.CharField(max_length=250)
    first_name = forms.CharField(max_length=200)
    last_name = forms.CharFblog.Category.nameield(max_length=200)
    email = forms.EmailField()
    password = forms.CharField(max_length=128)


    def save(self):
        username = self.changed_data['username']
        first_name = self.changed_data['first_name']
        last_name = self.changed_data['last_name']
        email = self.changed_data['email']
        password = self.changed_data['password']

        user = User.objects.create(
            username=username,
            first_name=first_name,
            last_name=last_name,
            email=email,
        )

        user.set_password(password)
        user.save()

        return user"""

class UserCreateForm(forms.ModelForm):
    class Meta:
        model = CustomUser
        fields = ("username" , "first_name" , "last_name" , "email" , "password")

    def save(self , commit=True):
        user = super().save(commit)
        user.set_password(self.cleaned_data['password'])

        user.save()

        return user

# class UserLoginForm(forms.Form):
#
#     username = forms.CharField(max_length=200)
#     password = forms.CharField(max_length=128)
#
#     # def clean(self):
#     #     username = self.cleaned_data['username']
#     #     password = self.cleaned_data['password']

class ProfileEditForm(forms.ModelForm):
    class Meta:
        model = CustomUser
        fields = ('profile_picture','username', 'first_name' , 'last_name', 'profession', 'email')

users/views.py
from django.contrib import messages
from django.contrib.auth import login, logout
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, redirect
from django.views import View
from .forms import UserCreateForm, ProfileEditForm
from .models import CustomUser

# Create your views here.

class RegisterView(View):
    def get(self, request):
        create_form = UserCreateForm()
        context = {
            "form": create_form,
        }
        return render(request, 'users/register.html', context)

    def post(self, request):
        create_form = UserCreateForm(data=request.POST)

        if create_form.is_valid():
            create_form.save()
            return redirect("users:login")
        else:
            context = {
                "form": create_form,
            }
            return render(request, 'users/register.html', context)


class LoginView(View):
    def get(self, request):
        login_form = AuthenticationForm()
        context = {
            "login_form": login_form,
        }
        return render(request, 'users/login.html', context)

    def post(self, request):
        login_form = AuthenticationForm(data=request.POST)

        if login_form.is_valid():
            user = login_form.get_user()
            login(request, user)

            messages.success(request, "You have successfully logged in.")

            return redirect("home")
        else:

            context = {
                "login_form": login_form,
            }
            return render(request, 'users/login.html', context)


class ProfileView(LoginRequiredMixin, View):
    def get(self, request , username):
        user = CustomUser.objects.get(username=username)
        context = {
            "user": user,
        }
        return render(request, 'users/profile.html', context)


class LogoutView(LoginRequiredMixin, View):
    def get(self, request):
        logout(request)
        messages.info(request, "You have successfully logged out.")
        return redirect("https://google.com/")


class ProfileUpdateView(LoginRequiredMixin, View):
    def get(self, request , username):
        user_update_form = ProfileEditForm(instance=request.user)
        context = {
            "form": user_update_form,
        }
        return render(request, 'users/profile_edit.html', context)

    def post(self, request , username):
        user_update_form = ProfileEditForm(instance=request.user, data=request.POST, files=request.FILES)
        context = {
            "form": user_update_form,
        }

        if user_update_form.is_valid():
            user_update_form.save()

            messages.success(request, 'You have successfully updated your profile.')

            return redirect(f"/users/profile/{request.user}/")

        return render(request, 'users/profile_edit.html', context)

templates/users/login.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %}Sign In{% endblock %}
{% block content %}
<div class="container">
    <div class="row mx-5">
        <div class="mx-4">
            <h2>Sign In</h2>
            <form method="POST">{% csrf_token %}
                {{ login_form | crispy }}
            <button class="btn btn-outline-success" type="submit">Login</button>
            <span class="ms-3">No account ? Create account <a href="{% url 'users:register' %}">Sign Up</a></span>
            </form>
        </div>
    </div>
</div>
{% endblock %}

templates/users/profile.html
{% extends 'base.html' %}
{% block title %}Profile{% endblock %}
{% block content %}
<div class="container">
    <div class="row mx-5">
        <div class="col-md-4">
            <img class="profile_photo_style" alt="profile picture" src="{{ user.profile_picture.url }}">
            <h3 class="mt-3">@{{ user.username }}</h3>
        </div>
        <div class="col-md-8">
            <h2 class="mb-4 mt-6">Profile</h2>
            <p class="form-control border-success">Username : {{ user.username }}</p>
            <p class="form-control border-success">First Name : {{ user.first_name }}</p>
            <p class="form-control border-success">Last Name : {{ user.last_name }} </p>
            <p class="form-control border-success">Email : {{ user.email }}</p>
            <p class="form-control border-success">Profession : {{ user.profession }}</p>
            <p class="form-control border-success">Joined : {{ user.date_joined | date:"M d, Y"}}</p>

            <div class="mt-4">
               <a href="{% url 'home' %}" class="btn btn-primary">Back</a>
                {% if user == request.user %}
               <a class="btn btn-success" href="{% url 'users:profile_edit' user.username %}">update</a>
                {% endif %}
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/users/profile_edit.html
sou{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %}Profile Edit{% endblock %}

{% block content %}
<div class="container">
    <div class="row mx-5">
        <div class="mx-4">
            <h2>Profile Edit</h2>
            <form method="post" enctype="multipart/form-data">{% csrf_token %}
                {{ form | crispy }}
             <a href="{% url 'users:profile' request.user %}" class="btn btn-primary">Back</a>
            <button type="submit" class="btn btn-outline-success">Save</button>
            </form>
        </div>
    </div>
</div>
{% endblock %}

templates/users/register.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %}Register{% endblock %}
{% block content %}
<div class="container">
    <div class="row mx-5">
        <div class="mx-4">
            <h2>Sign Up</h2>
            <form method="post">{% csrf_token %}
                {{ form | crispy }}
                <button class="btn btn-outline-success" type="submit">Sign Up</button>
            </form>
        </div>
    </div>
</div>
{% endblock %}